In [1]:
import pandas as pd
import numpy as np

# Create a sample DataFrame with missing values, duplicates, and inconsistent formatting
data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivy'],
    'Age': [25, 30, np.nan, 25, 35, 28, 40, 32, np.nan, 26],
    'City': ['New York', 'London', 'Paris', 'New York', 'Tokyo', 'London', 'Berlin', 'Sydney', 'Paris', 'Tokyo'],
    'Salary': [50000, 60000, 70000, 50000, 80000, 65000, 90000, 75000, 70000, 55000],
    'Date_Joined': ['2020-01-15', '2019-05-20', '2021-03-10', '2020-01-15', '2018-11-01', '2022-07-25', '2017-09-12', '2020-04-30', '2021-03-10', '2019-12-05'],
    'Email': ['alice@example.com', 'bob@example.com', 'charlie@example.com', 'ALICE@EXAMPLE.COM', 'david@example.com', 'eve@example.com', 'frank@example.com', 'grace@example.com', 'charlie@example.com', 'ivy@example.com']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
display(df)

# 1. Handling Missing Values
# Fill missing 'Age' values with the mean
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Drop rows with any remaining missing values (if any)
df.dropna(inplace=True)

# 2. Handling Duplicate Data
# Identify and remove duplicate rows based on all columns
df.drop_duplicates(inplace=True)

# Identify and remove duplicate rows based on specific columns (e.g., 'Name', 'Date_Joined')
df.drop_duplicates(subset=['Name', 'Date_Joined'], inplace=True)

# 3. Handling Inconsistent Formatting
# Convert 'Email' column to lowercase
df['Email'] = df['Email'].str.lower()

# Convert 'Date_Joined' to datetime objects
df['Date_Joined'] = pd.to_datetime(df['Date_Joined'])

# 4. Handling Outliers (Simple example: remove rows where Salary is below a threshold)
# In a real scenario, outlier detection is more complex and depends on the data distribution
df = df[df['Salary'] >= 50000]

print("\nCleaned DataFrame:")
display(df)

Original DataFrame:

   ID     Name   Age      City  Salary Date_Joined                Email
0   1    Alice  25.0  New York   50000  2020-01-15    alice@example.com
1   2      Bob  30.0    London   60000  2019-05-20      bob@example.com
2   3  Charlie   NaN     Paris   70000  2021-03-10  charlie@example.com
3   4    Alice  25.0  New York   50000  2020-01-15    ALICE@EXAMPLE.COM
4   5    David  35.0     Tokyo   80000  2018-11-01    david@example.com
5   6      Eve  28.0    London   65000  2022-07-25      eve@example.com
6   7    Frank  40.0    Berlin   90000  2017-09-12    frank@example.com
7   8    Grace  32.0    Sydney   75000  2020-04-30    grace@example.com
8   9    Heidi   NaN     Paris   70000  2021-03-10  charlie@example.com
9  10      Ivy  26.0     Tokyo   55000  2019-12-05      ivy@example.com

Cleaned DataFrame:

/tmp/ipython-input-4226272499.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

   ID     Name     Age      City  Salary Date_Joined                Email
0   1    Alice  25.000  New York   50000  2020-01-15    alice@example.com
1   2      Bob  30.000    London   60000  2019-05-20      bob@example.com
2   3  Charlie  30.125     Paris   70000  2021-03-10  charlie@example.com
4   5    David  35.000     Tokyo   80000  2018-11-01    david@example.com
5   6      Eve  28.000    London   65000  2022-07-25      eve@example.com
6   7    Frank  40.000    Berlin   90000  2017-09-12    frank@example.com
7   8    Grace  32.000    Sydney   75000  2020-04-30    grace@example.com
8   9    Heidi  30.125     Paris   70000  2021-03-10  charlie@example.com
9  10      Ivy  26.000     Tokyo   55000  2019-12-05      ivy@example.com